title: Tristan Williams # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a recent econometrics/business analytics graduate with an interest in everything to do with data 
  <br><br>
  Here you can see a few projects that I've done as well as a little bit about my background and experience 
  <br><br>
  <a href="https://www.linkedin.com/in/tdw75/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

